language: node_js
node_js:
  - 8.0
before_script:
  - npm install -g grunt-cli
  - npm install -g jasmine-node
branches:
  only:
    - master
script:
  - grunt build
notifications:
  email:
    recipients:
      - ksmwsk+travis@gmail.com
