language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g jasmine-node
script:
  - grunt
notifications:
  email:
    recipients:
      - support@globexdesigns.com